### PR TITLE
Update to Ruby 3.0.3

### PR DESCRIPTION
**Pull request by jbirdjavi**

### CODE REVIEW

**Review by dbenton9 — APPROVED** [review]
This looks good although GHA failed. I hit rerun hopefully it was just being tempermental.

**Comment by dbenton9** [comment]
Hmmm.... `DB Setup` on GHA keeps failing. I don't see why any of these changes would cause that though...

**Comment by jbirdjavi** [comment]
@dbenton9 Google pointed me to https://giters.com/Shopify/bootsnap/issues/378 based on the error. Looks like 3.0.3 and bootsnap weren't playing nice before.

**Comment by jbirdjavi** [comment]
@dbenton9 I'll let you merge this since you know more about this app. :)

**Comment by dbenton9** [comment]
Done 😄

**Pull request merged**
